My_User_Authentication/Login_app/urls.py
from django.conf.urls import url
from django.urls import path
from Login_app import views

# #settings added
from django.conf import settings
# # #static and static_url added
from django.conf.urls.static import static


app_name = 'Login_app'

urlpatterns = [
    path('', views.index, name='Home'),
    path('signup/', views.register, name='register' ),
    path('signin/', views.login_page, name='login'),
    path('user_login/', views.user_login, name='userLogin'),
    path('logout/', views.user_logout, name='logout'),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

My_User_Authentication/My_User_Authentication/urls.py
from django.contrib import admin
from django.urls import path


from django.conf.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login_app.urls')),
]

My_User_Authentication/Login_app/models.py
from django.db import models

#Django provided User Model imported
from django.contrib.auth.models import User


# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    facebook_id = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

My_User_Authentication/Login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from Login_app.models import UserInfo

class UserForm(forms.ModelForm):
    username = forms.CharField(label='User Name ',
    help_text ="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
    widget=forms.TextInput(attrs={
    'placeholder':'User Name','style':'width:300px; height:33px; border: 1px solid gray; border-radius:2px;'
    }))
    email = forms.CharField(label='Email ', widget=forms.TextInput(attrs={'type':'email',
    'placeholder':'Enter Email','style':'width:300px; height:33px; border: 1px solid gray; border-radius:2px;'
    }))
    password = forms.CharField(label='Passowrd ', widget=forms.PasswordInput(attrs={ 'type':'password',
    'placeholder':'Enter Passowrd','style':'width:300px; height:33px; border: 1px solid gray; border-radius:2px;'
    }))

    class Meta():
        model = User
        fields = ("username", "email", "password")

class UserInfoForm(forms.ModelForm):
    facebook_id = forms.CharField(label='Facebook Id ', widget=forms.TextInput(attrs={
    'placeholder':'Enter Facebook Id ULR','style':'width:300px; height:33px; border: 1px solid gray; border-radius:2px;'
    }))
    class Meta():
        model = UserInfo
        fields = ('facebook_id', 'profile_pic')

My_User_Authentication/Login_app/views.py
from django.shortcuts import render

from Login_app.forms import UserForm, UserInfoForm
# Create your views here.

#authenticate user, login user, and logout user function
from django.contrib.auth import authenticate, login, logout
#http response and redirect function
from django.http import HttpResponseRedirect, HttpResponse
#useing decorators and login_required we find user login or not.
from django.contrib.auth.decorators import login_required
#move one view to other view with urls
from django.urls import reverse

#User model added
from django.contrib.auth.models import User
#UserInfo model added
from Login_app.models import UserInfo



def login_page(request):

    diction={
        'title': 'Login | Authentication'
    }
    return render(request, 'Login_app/login.html', context=diction)

def user_login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login_app:Home'))
            else:
                return HttpResponse("Account is not active!!")
        else:
            return HttpResponse("Username or password was wrong!!")

    else:
        return HttpResponseRedirect(reverse('Login_app:login'))

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login_app:Home'))


def index(request):

    diction={
        'title': 'Home | Authentication'
    }
    if request.user.is_authenticated:
        current_user = request.user
        print(current_user.username)
        print(current_user.id)
        user_id = current_user.id
        user_basic_info = User.objects.get(pk=user_id)
        user_more_info = UserInfo.objects.get(user__id = user_id)
        diction = {
            'user_basic_info':user_basic_info,
            'user_more_info':user_more_info
        }
        diction.update({'title': 'Login-Home | Authentication'})
    return render(request, 'Login_app/index.html', context=diction)

def register(request):

    registered = False
    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        user_info_form = UserInfoForm(data=request.POST)

        if user_form.is_valid() and user_info_form.is_valid():

            user = user_form.save()#create a object of last added data
            user.set_password(user.password)#last added objects password enctyped by this
            user.save()

            user_info = user_info_form.save(commit=False)#creat object but not save
            user_info.user = user #one to one connection wih two model

            if 'profile_pic' in request.FILES:
                user_info.profile_pic = request.FILES['profile_pic']

            user_info.save()
            registered = True
    else:
        user_form = UserForm()
        user_info_form = UserInfoForm()

    diction = {
        'title': 'Register | Authentication',
        'user_form':user_form,
        'user_info_form':user_info_form,
        'registered':registered
    }
    return render(request, 'Login_app/register.html', context=diction)

My_User_Authentication/templates/Login_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- Latest compiled and minified CSS -->
 <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <!-- jQuery library -->
  <script src="{% static "js/jquery.min.js" %}"></script>
  <!-- Popper JS -->
  <script src="{% static "js/popper.min.js" %}"></script>
  <!-- Latest compiled JavaScript -->
  <script src="{% static "js/bootstrap.min.js" %}"></script>


  <!-- for table search  -->
  <script src="{% static "js/datatables.min.js" %}"></script>
  <script src="{% static "js/datatables.min.js.map" %}"></script>
  <script src="{% static "js/datatables-select.min.js" %}"></script>
  <script src="{% static "js/datatables-select.min.js.map" %}"></script>
  <title>{{ title }}</title>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-dark" >
    <button  class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
     <!-- <a class="navbar-brand" style="color:white" href="#">Logo</a> -->
      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active" >
          <a class="nav-link" style="color:white" href="{% url 'Login_app:Home' %}">Home</a>
        </li>

        {% if user.is_authenticated %}
        <li class="nav-item" >
          <a class="nav-link" style="color:white" href="{% url 'Login_app:logout' %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item" >
          <a class="nav-link" style="color:white" href="{% url 'Login_app:register' %}">Signup</a>
        </li>
        <li class="nav-item" >
          <a class="nav-link" style="color:white" href="{% url 'Login_app:login' %}">Login</a>
        </li>
        {% endif %}

    </div>
    <a class="navbar-brand" style="color:white" href="#">Logo</a>
  </nav>
<div class="container" style="padding-top:20px;">
{% block body_block %}

{% endblock %}
</div>
</body>
</html>
<script type="text/javascript">
$(document).ready(function () {
$('#dtBasicExample').DataTable();
$('.dataTables_length').addClass('bs-select');
});
</script>





<!-- <script src="{% static "js/bootstrap.js" %}"></script>
<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/mdb.js" %}"></script>
<script src="{% static "js/mdb.lite.min.js.map" %}"></script>
<script src="{% static "js/mdb.min.js" %}"></script>
<script src="{% static "js/mdb.min.js.map" %}"></script>
<script src="{% static "js/popper.js" %}"></script> -->

<!-- <script src="{% static "js/directives.min.js" %}"></script>
<script src="{% static "js/directives.min.js.map" %}"></script>
<script src="{% static "js/flag.min.js" %}"></script>
<script src="{% static "js/flag.min.js.map" %}"></script>
<script src="{% static "js/imagesloaded.pkgd.min.js" %}"></script>
<script src="{% static "js/imagesloaded.pkgd.min.js.map" %}"></script>
<script src="{% static "js/jquery.zmd.hierarchical-display.min.js" %}"></script>
<script src="{% static "js/jquery.zmd.hierarchical-display.min.js.map" %}"></script>
<script src="{% static "js/masonry.pkgd.min.js" %}"></script>
<script src="{% static "js/masonry.pkgd.min.js.map" %}"></script>

<script src="{% static "js/rating.min.js" %}"></script>
<script src="{% static "js/rating.min.js.map" %}"></script> -->

My_User_Authentication/templates/Login_app/index.html
{% extends 'Login_app/base.html' %}
{% load static %}
{% block body_block %}

{% if user.is_authenticated %}
<p> Hi {{ user_basic_info.username }}</p>
<p>Your email : {{ user_basic_info.email }}</p>
<p><a href="{{ user_more_info.facebook_id }}">Facebook </a></p>

<img src="/media/{{ user_more_info.profile_pic }}" alt="{{ user_more_info.profile_pic }}" width="200px">

{% else %}
<h1 align="center">You are not Login ...</h1>
<h2 align="center">Please, Login First...</h2>
{% endif %}
{% endblock %}

My_User_Authentication/templates/Login_app/login.html
{% extends 'Login_app/base.html' %}
{% load static %}
{% block body_block %}


<h3 align="center">Please Login ..</h3>
<div class="main">
    <div class="col-md-6 col-sm-12">
      <div class="login-form">
        <form enctype="multipart/form-data" action="{% url 'Login_app:userLogin' %}" method="POST">
            <div class="form-group">
              <label for="username">User Name : </label>
                <input type="text" class="form-control" name="username" placeholder="User Name">
            </div>
            <div class="form-group">
              <label>Password : </label>
               <input type="password" class="form-control" name="password" placeholder="Password">
            </div>
          {% csrf_token %}
            <input class="btn btn-secondary" type="submit" name="submit" value="Login">
          </form>
      </div>
    </div>
</div>


{% endblock %}

My_User_Authentication/templates/Login_app/register.html
{% extends 'Login_app/base.html' %}
{% load static %}
{% block body_block %}

{% if registered %}
<div align="center" class="alert alert-success" role="alert">
congratulations! your  successfully registered..
</div>
{% else %}
<h1 align="center">Register here ..</h1>

<div class="row" align="left" style="padding-top:20px;">
  <form enctype="multipart/form-data" method="POST">
      {{ user_form.as_p }}
      {{ user_info_form.as_p }}
      {% csrf_token %}
      <input class="btn btn-primary" type="submit" name="submit" value="Register">
  </form>
</div>
{% endif %}


{% endblock %}